language: node_js
node_js:
    - "6"
    - "8"
install:
    - npm install
cache:
  directories:
    - node_modules
notifications:
    email:
        recipients:
            - mateusgabimoreira@gmail.com
