language: node_js
node_js:
    - "6"
    - "8"
install:
    - npm install
build:
    - npm run build
deploy:
    provider: pages
    skip-cleanup: true
    github-token: 2606d5c9b368f8feb6d855e563964884df121204
    keep-history: true
    on:
        branch: master
cache:
  directories:
    - node_modules
notifications:
    email:
        recipients:
            - mateusgabimoreira@gmail.com
