language: node_js
node_js:
  - "8"
notifications:
  email:
    recipients:
      - mateusgabimoreira@gmail.com
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm test
before_deploy:
  - npm run dist
deploy:
  - npm run release
  on:
    branch: master
