language: node_js
node_js:
    - "6"
notifications:
    email:
        recipients:
            - mateusgabimoreira@gmail.com
install:
    - npm install
build:
    - npm run build
test:
    - npm test
after_success:
    - npm run semantic-release
cache:
  directories:
    - node_modules
