language: node_js

node_js:
  - "10"
  - "9"
  - "8"

script:
  - npm install
  - npm test

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npm run release
  on:
    branch: master

cache:
  directories:
    - node_modules

notifications:
    email:
        recipients:
            - mateusgabimoreira@gmail.com