language: node_js
node_js:
    - "6"
install:
    - npm install
build:
    - npm run dist
test:
    - npm test
deploy:
    - provider: script
    script: npm run release
    on:
        branch: master
cache:
  directories:
    - node_modules
notifications:
    email:
        recipients:
            - mateusgabimoreira@gmail.com