language: node_js
node_js:
    - "6"
install:
    - npm install
build:
    - npm run build
test:
    - npm test
deploy:
    provider: npm
    email: mateusgabimoreia@gmail.com
    api_key: $NPM_TOKEN
    on:
        branch: master
cache:
  directories:
    - node_modules
notifications:
    email:
        recipients:
            - mateusgabimoreira@gmail.com
